name: 'build'

on:
  push:
    branches:
    - main
  # pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2


      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2        
        with:
          context: ./hello-app-v1
          file: ./hello-app-v1/Dockerfile
          tags: ghcr.io/antek51/hello-app:1
